In [351]:
import pandas as pd
import numpy as np
#import matplotlib.pyplot as plt

In [352]:
df = pd.read_csv('train.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [353]:
df['gender']=0
df['gender'][df['Sex']=='male']=0
df['gender'][df['Sex']=='female']=1
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
 12  gender       891 non-null    int64
dtypes: float64(2), int64(6), object(5)
memory usage: 90.6+ KB

<ipython-input-353-0879024265e9>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gender'][df['Sex']=='male']=0
<ipython-input-353-0879024265e9>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gender'][df['Sex']=='female']=1

In [354]:
df_20 = df.iloc[:200].copy()

In [355]:
df_20

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,gender
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,1,1,"Lurette, Miss. Elise",female,58.0,0,0,PC 17569,146.5208,B80,C,1
196,197,0,3,"Mernagh, Mr. Robert",male,NaN,0,0,368703,7.7500,NaN,Q,0
197,198,0,3,"Olsen, Mr. Karl Siegwart Andreas",male,42.0,0,1,4579,8.4042,NaN,S,0
198,199,1,3,"Madigan, Miss. Margaret ""Maggie""",female,NaN,0,0,370370,7.7500,NaN,Q,1
199,200,0,2,"Yrois, Miss. Henriette (""Mrs Harbeck"")",female,24.0,0,0,248747,13.0000,NaN,S,1

In [356]:
df_20.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  200 non-null    int64
 1   Survived     200 non-null    int64
 2   Pclass       200 non-null    int64
 3   Name         200 non-null    object
 4   Sex          200 non-null    object
 5   Age          159 non-null    float64
 6   SibSp        200 non-null    int64
 7   Parch        200 non-null    int64
 8   Ticket       200 non-null    object
 9   Fare         200 non-null    float64
 10  Cabin        40 non-null     object
 11  Embarked     199 non-null    object
 12  gender       200 non-null    int64
dtypes: float64(2), int64(6), object(5)
memory usage: 20.4+ KB

In [357]:
df_20.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  200 non-null    int64
 1   Survived     200 non-null    int64
 2   Pclass       200 non-null    int64
 3   Name         200 non-null    object
 4   Sex          200 non-null    object
 5   Age          159 non-null    float64
 6   SibSp        200 non-null    int64
 7   Parch        200 non-null    int64
 8   Ticket       200 non-null    object
 9   Fare         200 non-null    float64
 10  Cabin        40 non-null     object
 11  Embarked     199 non-null    object
 12  gender       200 non-null    int64
dtypes: float64(2), int64(6), object(5)
memory usage: 20.4+ KB

In [358]:
mean = df_20['Age'].mean()
df_20['Age'].fillna(mean, inplace=True)
age = df_20[['Age']]
age.shape

(200, 1)

In [359]:
gender = df_20[['gender']]
gender.shape

(200, 1)

In [360]:
survival = df_20['Survived']
survival.shape

(200,)

In [361]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(gender, survival)
model.coef_, model.intercept_

(array([[2.44157112]]), array([-1.66971845]))

In [362]:
#coef = np.array([[0.02705495]])
#bias =  np.array([-0.75660013])
#coef = np.array([[1.61091612]])
#bias =  np.array([-0.89487946])
coef =np.array(model.coef_)
bias = np.array(model.intercept_)

<h3>Define the log-odds function</h3>

In [363]:
def log_odds(features, coefficients, bias):
    return np.dot(features, coefficients) + bias

In [364]:
result_log_odds = log_odds(gender, coef, bias)
result_log_odds

array([[-1.66971845],
       [ 0.77185267],
       [ 0.77185267],
       [ 0.77185267],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [ 0.77185267],
       [ 0.77185267],
       [ 0.77185267],
       [ 0.77185267],
       [-1.66971845],
       [-1.66971845],
       [ 0.77185267],
       [ 0.77185267],
       [-1.66971845],
       [-1.66971845],
       [ 0.77185267],
       [ 0.77185267],
       [-1.66971845],
       [-1.66971845],
       [ 0.77185267],
       [-1.66971845],
       [ 0.77185267],
       [ 0.77185267],
       [-1.66971845],
       [-1.66971845],
       [ 0.77185267],
       [-1.66971845],
       [-1.66971845],
       [ 0.77185267],
       [ 0.77185267],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [ 0.77185267],
       [ 0.77185267],
       [ 0.77185267],
       [ 0.77185267],
       [-1.66971845],
       [ 0.77185267],
       [ 0.77185267],
       [-1.66971845],
       [-1.66971845],
       [ 0.77185267],
       [-1.66971845],
       [ 0.77185267],
       [-1.66971845],
       [-1.66971845],
       [ 0.77185267],
       [ 0.77185267],
       [-1.66971845],
       [-1.66971845],
       [ 0.77185267],
       [-1.66971845],
       [ 0.77185267],
       [-1.66971845],
       [-1.66971845],
       [ 0.77185267],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [ 0.77185267],
       [-1.66971845],
       [ 0.77185267],
       [-1.66971845],
       [-1.66971845],
       [ 0.77185267],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [ 0.77185267],
       [-1.66971845],
       [-1.66971845],
       [ 0.77185267],
       [-1.66971845],
       [ 0.77185267],
       [ 0.77185267],
       [-1.66971845],
       [-1.66971845],
       [ 0.77185267],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [ 0.77185267],
       [-1.66971845],
       [ 0.77185267],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [ 0.77185267],
       [-1.66971845],
       [-1.66971845],
       [ 0.77185267],
       [-1.66971845],
       [ 0.77185267],
       [-1.66971845],
       [ 0.77185267],
       [ 0.77185267],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [ 0.77185267],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [ 0.77185267],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [ 0.77185267],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [ 0.77185267],
       [ 0.77185267],
       [-1.66971845],
       [-1.66971845],
       [ 0.77185267],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [ 0.77185267],
       [ 0.77185267],
       [ 0.77185267],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [ 0.77185267],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [ 0.77185267],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [ 0.77185267],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [ 0.77185267],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [ 0.77185267],
       [ 0.77185267],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [ 0.77185267],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [ 0.77185267],
       [-1.66971845],
       [-1.66971845],
       [ 0.77185267],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [ 0.77185267],
       [-1.66971845],
       [ 0.77185267],
       [-1.66971845],
       [-1.66971845],
       [-1.66971845],
       [ 0.77185267],
       [-1.66971845],
       [ 0.77185267],
       [-1.66971845],
       [ 0.77185267],
       [ 0.77185267],
       [-1.66971845],
       [-1.66971845],
       [ 0.77185267],
       [ 0.77185267]])

<h3>Define the sigmoid function</h3>

In [365]:
def sigmoid(log_odds):
    denominator = 1 + np.exp(-log_odds)
    return 1 / denominator

In [366]:
p_hat = sigmoid(result_log_odds)
p_hat

array([[0.15846172],
       [0.68392153],
       [0.68392153],
       [0.68392153],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.68392153],
       [0.68392153],
       [0.68392153],
       [0.68392153],
       [0.15846172],
       [0.15846172],
       [0.68392153],
       [0.68392153],
       [0.15846172],
       [0.15846172],
       [0.68392153],
       [0.68392153],
       [0.15846172],
       [0.15846172],
       [0.68392153],
       [0.15846172],
       [0.68392153],
       [0.68392153],
       [0.15846172],
       [0.15846172],
       [0.68392153],
       [0.15846172],
       [0.15846172],
       [0.68392153],
       [0.68392153],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.68392153],
       [0.68392153],
       [0.68392153],
       [0.68392153],
       [0.15846172],
       [0.68392153],
       [0.68392153],
       [0.15846172],
       [0.15846172],
       [0.68392153],
       [0.15846172],
       [0.68392153],
       [0.15846172],
       [0.15846172],
       [0.68392153],
       [0.68392153],
       [0.15846172],
       [0.15846172],
       [0.68392153],
       [0.15846172],
       [0.68392153],
       [0.15846172],
       [0.15846172],
       [0.68392153],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.68392153],
       [0.15846172],
       [0.68392153],
       [0.15846172],
       [0.15846172],
       [0.68392153],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.68392153],
       [0.15846172],
       [0.15846172],
       [0.68392153],
       [0.15846172],
       [0.68392153],
       [0.68392153],
       [0.15846172],
       [0.15846172],
       [0.68392153],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.68392153],
       [0.15846172],
       [0.68392153],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.68392153],
       [0.15846172],
       [0.15846172],
       [0.68392153],
       [0.15846172],
       [0.68392153],
       [0.15846172],
       [0.68392153],
       [0.68392153],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.68392153],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.68392153],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.68392153],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.68392153],
       [0.68392153],
       [0.15846172],
       [0.15846172],
       [0.68392153],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.68392153],
       [0.68392153],
       [0.68392153],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.68392153],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.68392153],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.68392153],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.68392153],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.68392153],
       [0.68392153],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.68392153],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.68392153],
       [0.15846172],
       [0.15846172],
       [0.68392153],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.68392153],
       [0.15846172],
       [0.68392153],
       [0.15846172],
       [0.15846172],
       [0.15846172],
       [0.68392153],
       [0.15846172],
       [0.68392153],
       [0.15846172],
       [0.68392153],
       [0.68392153],
       [0.15846172],
       [0.15846172],
       [0.68392153],
       [0.68392153]])

In [367]:
survival = survival.to_numpy().reshape(-1, 1)

In [368]:
def log_loss(probabilities, labels):
    return (-1 / labels.shape[0]) * np.sum(labels * np.log(probabilities) + (1-labels) * np.log(1-probabilities))

In [369]:
cost = log_loss(p_hat, survival)
cost

0.4736065568826293

In [370]:
def predict(features, coefficients, bias, threshold):
    result_log_odds = log_odds(features, coefficients, bias)
    p_hat = sigmoid(result_log_odds)
    return np.where(p_hat >= threshold, 1, 0)

In [371]:
predicted_result = predict(gender, coef, bias, 0.5)
predicted_result

array([[0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1]])

<h3>Sci-kit Learn implementation</h3>

In [372]:
logit_reg = LogisticRegression()

In [373]:
from sklearn.preprocessing import StandardScaler

z_score_scaler = StandardScaler()
gender_scaled = z_score_scaler.fit_transform(gender)

In [374]:
logit_reg.fit(gender_scaled, survival.ravel())

LogisticRegression()

In [375]:
print(logit_reg.coef_)
print(logit_reg.intercept_)

[[1.27956255]]
[-0.83089365]

In [376]:
# Testing if the parameter vector theta given in step 5 is the optimized one.
result_log_odds_sk = log_odds(gender_scaled, logit_reg.coef_, logit_reg.intercept_)
p_hat_sk = sigmoid(result_log_odds_sk)
cost_sk = log_loss(p_hat_sk, survival)
print(cost_sk)

0.47184271641294234

In [379]:
df_20_new = df.iloc[201:230].copy()
df_20_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 201 to 229
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  29 non-null     int64
 1   Survived     29 non-null     int64
 2   Pclass       29 non-null     int64
 3   Name         29 non-null     object
 4   Sex          29 non-null     object
 5   Age          25 non-null     float64
 6   SibSp        29 non-null     int64
 7   Parch        29 non-null     int64
 8   Ticket       29 non-null     object
 9   Fare         29 non-null     float64
 10  Cabin        5 non-null      object
 11  Embarked     29 non-null     object
 12  gender       29 non-null     int64
dtypes: float64(2), int64(6), object(5)
memory usage: 3.1+ KB

In [380]:
#mean = df_20_new['Age'].mean()
#df_20_new['Age'].fillna(mean, inplace=True)
gender_new = df_20_new[['gender']]
gender_new_scaled = z_score_scaler.fit_transform(gender_new)

predictions = logit_reg.predict(gender_new_scaled)
print(predictions)
print(df_20_new['Survived'].ravel())

[0 0 0 0 1 0 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 0 1 0 1 0 0 0 1 0 1 0 0 0]